version: "3.8"
services:
  webserver:
    container_name: blog-serve
    build:
      context: .
    restart: always
    ports:
      - "3001:80"
    volumes:
      - "D:/Projetos/blog/blog:/var/www/html/"
  #  environment:
  #    APP_ENV: local
  #    APP_DEBUG: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
      container_name: blog-mysql
      image: mysql
      restart: "always"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
      ports:
          - "3308:3306"
  phpmyadmin:
      container_name: blog-phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      restart: "always"
      environment:
          PMA_HOST: db
          PMA_USER: root
          PMA_PASSWORD: root
      ports:
          - "8080:80"